# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jeanne Simonelli
email: mbussa@unomaha.edu
  #American, b. 1947. Genres: Novellas/Short stories, Poetry, Anthropology/Ethnology. Career: State University of New York College at Oneonta, professor of anthropology, 1985-99; Wake Forest University, chair and professor of anthropology, 1999-. Gives readings from her works in poetry and short fiction. Publications: Two Boys, a Girl, and Enough! Reproductive and Economic Decision Making on the Mexican Periphery, 1986; Too Wet to Plow: The Family Farm in Transition, 1990; Crossing between Worlds: The Navajos of Canyon de Chelly, 1997; The Sea of Our Dreams: Zapatista Development and Autonomy in Chiapas. Contributor to books. Contributor of articles and poems to journals
description: >- #
baseurl: "/digitalhistorysite2" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: N/A 
github_username:  MinaBussa

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
